// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	xdpcountMapPktCount      = "pkt_count"
	xdpcountProgXdpCountPkts = "xdp_count_pkts"
)

// loadXdpcount returns the embedded CollectionSpec for xdpcount.
func loadXdpcount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpcountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpcount: %w", err)
	}

	return spec, err
}

// loadXdpcountObjects loads xdpcount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpcountObjects
//	*xdpcountPrograms
//	*xdpcountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpcountObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpcount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpcountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpcountSpecs struct {
	xdpcountProgramSpecs
	xdpcountMapSpecs
	xdpcountVariableSpecs
}

// xdpcountProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpcountProgramSpecs struct {
	XdpCountPkts *ebpf.ProgramSpec `ebpf:"xdp_count_pkts"`
}

// xdpcountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpcountMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
}

// xdpcountVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpcountVariableSpecs struct {
}

// xdpcountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpcountObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpcountObjects struct {
	xdpcountPrograms
	xdpcountMaps
	xdpcountVariables
}

func (o *xdpcountObjects) Close() error {
	return _XdpcountClose(
		&o.xdpcountPrograms,
		&o.xdpcountMaps,
	)
}

// xdpcountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpcountObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpcountMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
}

func (m *xdpcountMaps) Close() error {
	return _XdpcountClose(
		m.PktCount,
	)
}

// xdpcountVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpcountObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpcountVariables struct {
}

// xdpcountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpcountObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpcountPrograms struct {
	XdpCountPkts *ebpf.Program `ebpf:"xdp_count_pkts"`
}

func (p *xdpcountPrograms) Close() error {
	return _XdpcountClose(
		p.XdpCountPkts,
	)
}

func _XdpcountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpcount_bpfeb.o
var _XdpcountBytes []byte
